
let progIds = [];
progIds.push(db.programas.insertOne({ codigo: "ISOFT", nombre: "Ingeniería de Software", creditos_totales: 140, semestres: 10, requisitos_graduacion: ["Proyecto de grado", "Pasantía"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "MED", nombre: "Medicina", creditos_totales: 180, semestres: 12, requisitos_graduacion: ["Rotaciones clínicas"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "DER", nombre: "Derecho", creditos_totales: 150, semestres: 10, requisitos_graduacion: ["Examen estatal"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "ADM", nombre: "Administración de Empresas", creditos_totales: 130, semestres: 8, requisitos_graduacion: ["Plan de negocio"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "BIO", nombre: "Biología", creditos_totales: 135, semestres: 9, requisitos_graduacion: ["Tesis"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "INGCIV", nombre: "Ingeniería Civil", creditos_totales: 160, semestres: 10, requisitos_graduacion: ["Proyecto estructural"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "PSI", nombre: "Psicología", creditos_totales: 140, semestres: 10, requisitos_graduacion: ["Práctica clínica"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "ECO", nombre: "Economía", creditos_totales: 120, semestres: 8, requisitos_graduacion: ["Análisis económico"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "ARQ", nombre: "Arquitectura", creditos_totales: 170, semestres: 11, requisitos_graduacion: ["Diseño final"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "COM", nombre: "Comunicación Social", creditos_totales: 130, semestres: 8, requisitos_graduacion: ["Portafolio"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "ELE", nombre: "Ingeniería Eléctrica", creditos_totales: 150, semestres: 10, requisitos_graduacion: ["Proyecto eléctrico"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "FIL", nombre: "Filosofía", creditos_totales: 120, semestres: 8, requisitos_graduacion: ["Ensayo"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "QUI", nombre: "Química", creditos_totales: 140, semestres: 9, requisitos_graduacion: ["Laboratorio avanzado"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "MAT", nombre: "Matemáticas", creditos_totales: 130, semestres: 8, requisitos_graduacion: ["Teorema original"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "HIS", nombre: "Historia", creditos_totales: 120, semestres: 8, requisitos_graduacion: ["Investigación histórica"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "ENF", nombre: "Enfermería", creditos_totales: 150, semestres: 10, requisitos_graduacion: ["Práctica hospitalaria"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "FIS", nombre: "Física", creditos_totales: 140, semestres: 9, requisitos_graduacion: ["Experimento"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "LIT", nombre: "Literatura", creditos_totales: 120, semestres: 8, requisitos_graduacion: ["Análisis literario"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "MUS", nombre: "Música", creditos_totales: 130, semestres: 8, requisitos_graduacion: ["Concierto"], plan_estudio: [] }).insertedId);
progIds.push(db.programas.insertOne({ codigo: "ART", nombre: "Artes Plásticas", creditos_totales: 140, semestres: 9, requisitos_graduacion: ["Exposición"], plan_estudio: [] }).insertedId);
print("Programas insertados. IDs: " + progIds);

let matIds = [];
matIds.push(db.materias.insertOne({ codigo: "BD101", nombre: "Bases de Datos I", creditos: 4, prerrequisitos: [], contenido: "Introducción a NoSQL", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "MAT101", nombre: "Matemáticas Básicas", creditos: 3, prerrequisitos: [], contenido: "Álgebra", tipo: "Fundamentación" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "HIS201", nombre: "Historia del Derecho", creditos: 3, prerrequisitos: ["DER101"], contenido: "Historia legal", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "ADM101", nombre: "Introducción a Administración", creditos: 3, prerrequisitos: [], contenido: "Gestión básica", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "BIO101", nombre: "Biología General", creditos: 4, prerrequisitos: [], contenido: "Células y ecosistemas", tipo: "Fundamentación" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "CIV201", nombre: "Estructuras I", creditos: 4, prerrequisitos: ["MAT101"], contenido: "Diseño estructural", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "PSI101", nombre: "Psicología Introductoria", creditos: 3, prerrequisitos: [], contenido: "Comportamiento humano", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "ECO101", nombre: "Economía Básica", creditos: 3, prerrequisitos: [], contenido: "Microeconomía", tipo: "Fundamentación" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "ARQ101", nombre: "Diseño Arquitectónico I", creditos: 5, prerrequisitos: [], contenido: "Planos básicos", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "COM101", nombre: "Comunicación Oral", creditos: 3, prerrequisitos: [], contenido: "Técnicas de habla", tipo: "Electiva" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "ELE101", nombre: "Circuitos Eléctricos", creditos: 4, prerrequisitos: ["MAT101"], contenido: "Ohm y Kirchhoff", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "FIL101", nombre: "Filosofía Antigua", creditos: 3, prerrequisitos: [], contenido: "Sócrates y Platón", tipo: "Fundamentación" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "QUI101", nombre: "Química General", creditos: 4, prerrequisitos: [], contenido: "Átomos y moléculas", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "MAT201", nombre: "Cálculo Avanzado", creditos: 4, prerrequisitos: ["MAT101"], contenido: "Integrales", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "HIS101", nombre: "Historia Mundial", creditos: 3, prerrequisitos: [], contenido: "Épocas históricas", tipo: "Electiva" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "ENF101", nombre: "Anatomía Humana", creditos: 4, prerrequisitos: [], contenido: "Sistemas corporales", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "FIS101", nombre: "Física Clásica", creditos: 4, prerrequisitos: ["MAT101"], contenido: "Mecánica newtoniana", tipo: "Fundamentación" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "LIT101", nombre: "Literatura Universal", creditos: 3, prerrequisitos: [], contenido: "Obras clásicas", tipo: "Electiva" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "MUS101", nombre: "Teoría Musical", creditos: 3, prerrequisitos: [], contenido: "Notas y escalas", tipo: "Obligatoria" }).insertedId);
matIds.push(db.materias.insertOne({ codigo: "ART101", nombre: "Dibujo Básico", creditos: 3, prerrequisitos: [], contenido: "Técnicas de arte", tipo: "Fundamentación" }).insertedId);
print("Materias insertadas. IDs: " + matIds);

let estIds = [];
estIds.push(db.estudiantes.insertOne({ codigo: "EST001", nombre: "María López", email: "maria@uni.edu.co", programa: {id: progIds[0], nombre: "Ingeniería de Software"}, fecha_nacimiento: ISODate("2003-05-15"), semestre_actual: 5, promedio_acumulado: 4.2, estado: "Activo", materias_cursadas: [{materia_id: matIds[0], codigo: "BD101", nombre: "Bases de Datos I", periodo: "2024-1", nota_final: 4.5, creditos: 4}], creditos_cursados: 85 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST002", nombre: "Juan Pérez", email: "juan@uni.edu.co", programa: {id: progIds[1], nombre: "Medicina"}, fecha_nacimiento: ISODate("2004-02-10"), semestre_actual: 3, promedio_acumulado: 2.8, estado: "Activo", materias_cursadas: [{materia_id: matIds[1], codigo: "MAT101", nombre: "Matemáticas Básicas", periodo: "2024-1", nota_final: 2.5, creditos: 3}], creditos_cursados: 40 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST003", nombre: "Ana García", email: "ana@uni.edu.co", programa: {id: progIds[2], nombre: "Derecho"}, fecha_nacimiento: ISODate("2002-11-20"), semestre_actual: 10, promedio_acumulado: 4.8, estado: "Graduado", materias_cursadas: [{materia_id: matIds[2], codigo: "HIS201", nombre: "Historia del Derecho", periodo: "2024-2", nota_final: 4.9, creditos: 3}], creditos_cursados: 150 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST004", nombre: "Carlos Ramírez", email: "carlos@uni.edu.co", programa: {id: progIds[3], nombre: "Administración de Empresas"}, fecha_nacimiento: ISODate("2005-07-05"), semestre_actual: 2, promedio_acumulado: 3.5, estado: "Activo", materias_cursadas: [], creditos_cursados: 20 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST005", nombre: "Laura Martínez", email: "laura@uni.edu.co", programa: {id: progIds[4], nombre: "Biología"}, fecha_nacimiento: ISODate("2003-09-30"), semestre_actual: 6, promedio_acumulado: 2.4, estado: "Activo", materias_cursadas: [{materia_id: matIds[4], codigo: "BIO101", nombre: "Biología General", periodo: "2024-1", nota_final: 2.0, creditos: 4}], creditos_cursados: 60 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST006", nombre: "Diego Hernández", email: "diego@uni.edu.co", programa: {id: progIds[5], nombre: "Ingeniería Civil"}, fecha_nacimiento: ISODate("2004-04-12"), semestre_actual: 4, promedio_acumulado: 3.9, estado: "Inactivo", materias_cursadas: [{materia_id: matIds[5], codigo: "CIV201", nombre: "Estructuras I", periodo: "2024-2", nota_final: 4.0, creditos: 4}], creditos_cursados: 50 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST007", nombre: "Sofía Torres", email: "sofia@uni.edu.co", programa: {id: progIds[6], nombre: "Psicología"}, fecha_nacimiento: ISODate("2002-12-01"), semestre_actual: 7, promedio_acumulado: 4.1, estado: "Activo", materias_cursadas: [{materia_id: matIds[6], codigo: "PSI101", nombre: "Psicología Introductoria", periodo: "2024-1", nota_final: 4.2, creditos: 3}, {materia_id: matIds[7], codigo: "ECO101", nombre: "Economía Básica", periodo: "2024-2", nota_final: 4.0, creditos: 3}], creditos_cursados: 90 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST008", nombre: "Miguel Vargas", email: "miguel@uni.edu.co", programa: {id: progIds[7], nombre: "Economía"}, fecha_nacimiento: ISODate("2005-03-18"), semestre_actual: 1, promedio_acumulado: 3.0, estado: "Retirado", materias_cursadas: [], creditos_cursados: 0 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST009", nombre: "Elena Ruiz", email: "elena@uni.edu.co", programa: {id: progIds[8], nombre: "Arquitectura"}, fecha_nacimiento: ISODate("2003-06-25"), semestre_actual: 5, promedio_acumulado: 4.3, estado: "Activo", materias_cursadas: [{materia_id: matIds[8], codigo: "ARQ101", nombre: "Diseño Arquitectónico I", periodo: "2024-1", nota_final: 4.5, creditos: 5}], creditos_cursados: 80 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST010", nombre: "Pablo Gómez", email: "pablo@uni.edu.co", programa: {id: progIds[9], nombre: "Comunicación Social"}, fecha_nacimiento: ISODate("2004-08-14"), semestre_actual: 3, promedio_acumulado: 3.7, estado: "Activo", materias_cursadas: [{materia_id: matIds[9], codigo: "COM101", nombre: "Comunicación Oral", periodo: "2024-2", nota_final: 3.8, creditos: 3}], creditos_cursados: 40 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST011", nombre: "Isabela Fernández", email: "isabela@uni.edu.co", programa: {id: progIds[10], nombre: "Ingeniería Eléctrica"}, fecha_nacimiento: ISODate("2002-10-09"), semestre_actual: 8, promedio_acumulado: 4.0, estado: "Activo", materias_cursadas: [{materia_id: matIds[10], codigo: "ELE101", nombre: "Circuitos Eléctricos", periodo: "2024-1", nota_final: 4.1, creditos: 4}], creditos_cursados: 110 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST012", nombre: "Ricardo López", email: "ricardo@uni.edu.co", programa: {id: progIds[11], nombre: "Filosofía"}, fecha_nacimiento: ISODate("2005-01-22"), semestre_actual: 2, promedio_acumulado: 2.9, estado: "Activo", materias_cursadas: [{materia_id: matIds[11], codigo: "FIL101", nombre: "Filosofía Antigua", periodo: "2024-1", nota_final: 2.7, creditos: 3}], creditos_cursados: 30 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST013", nombre: "Valeria Sánchez", email: "valeria@uni.edu.co", programa: {id: progIds[12], nombre: "Química"}, fecha_nacimiento: ISODate("2003-04-03"), semestre_actual: 6, promedio_acumulado: 4.4, estado: "Graduado", materias_cursadas: [{materia_id: matIds[12], codigo: "QUI101", nombre: "Química General", periodo: "2024-2", nota_final: 4.6, creditos: 4}], creditos_cursados: 140 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST014", nombre: "Andrés Morales", email: "andres@uni.edu.co", programa: {id: progIds[13], nombre: "Matemáticas"}, fecha_nacimiento: ISODate("2004-05-17"), semestre_actual: 4, promedio_acumulado: 3.6, estado: "Activo", materias_cursadas: [{materia_id: matIds[13], codigo: "MAT201", nombre: "Cálculo Avanzado", periodo: "2024-1", nota_final: 3.5, creditos: 4}], creditos_cursados: 50 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST015", nombre: "Camila Ortiz", email: "camila@uni.edu.co", programa: {id: progIds[14], nombre: "Historia"}, fecha_nacimiento: ISODate("2002-07-28"), semestre_actual: 9, promedio_acumulado: 4.5, estado: "Activo", materias_cursadas: [{materia_id: matIds[14], codigo: "HIS101", nombre: "Historia Mundial", periodo: "2024-2", nota_final: 4.7, creditos: 3}], creditos_cursados: 120 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST016", nombre: "Sebastián Castro", email: "sebastian@uni.edu.co", programa: {id: progIds[15], nombre: "Enfermería"}, fecha_nacimiento: ISODate("2005-09-11"), semestre_actual: 1, promedio_acumulado: 3.2, estado: "Retirado", materias_cursadas: [], creditos_cursados: 0 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST017", nombre: "Natalia Ríos", email: "natalia@uni.edu.co", programa: {id: progIds[16], nombre: "Física"}, fecha_nacimiento: ISODate("2003-11-04"), semestre_actual: 5, promedio_acumulado: 4.0, estado: "Activo", materias_cursadas: [{materia_id: matIds[16], codigo: "FIS101", nombre: "Física Clásica", periodo: "2024-1", nota_final: 4.2, creditos: 4}], creditos_cursados: 70 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST018", nombre: "Gabriel Mendoza", email: "gabriel@uni.edu.co", programa: {id: progIds[17], nombre: "Literatura"}, fecha_nacimiento: ISODate("2004-12-19"), semestre_actual: 3, promedio_acumulado: 3.8, estado: "Activo", materias_cursadas: [{materia_id: matIds[17], codigo: "LIT101", nombre: "Literatura Universal", periodo: "2024-2", nota_final: 3.9, creditos: 3}], creditos_cursados: 40 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST019", nombre: "Valentina Jiménez", email: "valentina@uni.edu.co", programa: {id: progIds[18], nombre: "Música"}, fecha_nacimiento: ISODate("2002-02-08"), semestre_actual: 7, promedio_acumulado: 4.6, estado: "Activo", materias_cursadas: [{materia_id: matIds[18], codigo: "MUS101", nombre: "Teoría Musical", periodo: "2024-1", nota_final: 4.8, creditos: 3}], creditos_cursados: 100 }).insertedId);
estIds.push(db.estudiantes.insertOne({ codigo: "EST020", nombre: "Mateo Navarro", email: "mateo@uni.edu.co", programa: {id: progIds[19], nombre: "Artes Plásticas"}, fecha_nacimiento: ISODate("2005-03-26"), semestre_actual: 2, promedio_acumulado: 2.6, estado: "Activo", materias_cursadas: [{materia_id: matIds[19], codigo: "ART101", nombre: "Dibujo Básico", periodo: "2024-1", nota_final: 2.3, creditos: 3}], creditos_cursados: 20 }).insertedId);
print("Estudiantes insertados. IDs: " + estIds);

let profIds = [];
profIds.push(db.profesores.insertOne({ codigo: "PROF001", nombre: "Dr. Carlos Ruiz", email: "carlos@uni.edu.co", especialidades: ["Bases de Datos", "IA"], materias_asignadas: [{materia_id: matIds[0], periodo: "2025-1", horario: "Lun 8am"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF002", nombre: "Dra. Elena Soto", email: "elena@uni.edu.co", especialidades: ["Medicina Interna"], materias_asignadas: [{materia_id: matIds[1], periodo: "2025-1", horario: "Mar 9am"}, {materia_id: matIds[2], periodo: "2025-1", horario: "Mie 10am"}, {materia_id: matIds[3], periodo: "2025-2", horario: "Jue 11am"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF003", nombre: "Ing. Ana López", email: "ana.prof@uni.edu.co", especialidades: ["Derecho Civil"], materias_asignadas: [{materia_id: matIds[2], periodo: "2025-1", horario: "Vie 8am"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF004", nombre: "Dr. Juan Martínez", email: "juan.prof@uni.edu.co", especialidades: ["Administración"], materias_asignadas: [{materia_id: matIds[3], periodo: "2025-2", horario: "Lun 2pm"}, {materia_id: matIds[4], periodo: "2025-2", horario: "Mar 3pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF005", nombre: "Dra. Laura Gómez", email: "laura.prof@uni.edu.co", especialidades: ["Biología Molecular"], materias_asignadas: [{materia_id: matIds[4], periodo: "2025-1", horario: "Mie 4pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF006", nombre: "Ing. Diego Hernández", email: "diego.prof@uni.edu.co", especialidades: ["Ingeniería Estructural"], materias_asignadas: [{materia_id: matIds[5], periodo: "2025-1", horario: "Jue 5pm"}, {materia_id: matIds[6], periodo: "2025-2", horario: "Vie 6pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF007", nombre: "Dra. Sofía Torres", email: "sofia.prof@uni.edu.co", especialidades: ["Psicología Clínica"], materias_asignadas: [{materia_id: matIds[6], periodo: "2025-1", horario: "Lun 7pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF008", nombre: "Dr. Miguel Vargas", email: "miguel.prof@uni.edu.co", especialidades: ["Economía Macroeconómica"], materias_asignadas: [{materia_id: matIds[7], periodo: "2025-1", horario: "Mar 8pm"}, {materia_id: matIds[8], periodo: "2025-2", horario: "Mie 9pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF009", nombre: "Arq. Elena Ruiz", email: "elena.prof@uni.edu.co", especialidades: ["Diseño Urbano"], materias_asignadas: [{materia_id: matIds[8], periodo: "2025-1", horario: "Jue 10pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF010", nombre: "Dr. Pablo Gómez", email: "pablo.prof@uni.edu.co", especialidades: ["Comunicación Digital"], materias_asignadas: [{materia_id: matIds[9], periodo: "2025-1", horario: "Vie 11am"}, {materia_id: matIds[10], periodo: "2025-2", horario: "Lun 12pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF011", nombre: "Ing. Isabela Fernández", email: "isabela.prof@uni.edu.co", especialidades: ["Electrónica"], materias_asignadas: [{materia_id: matIds[10], periodo: "2025-1", horario: "Mar 1pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF012", nombre: "Dr. Ricardo López", email: "ricardo.prof@uni.edu.co", especialidades: ["Filosofía Moderna"], materias_asignadas: [{materia_id: matIds[11], periodo: "2025-1", horario: "Mie 2pm"}, {materia_id: matIds[12], periodo: "2025-2", horario: "Jue 3pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF013", nombre: "Dra. Valeria Sánchez", email: "valeria.prof@uni.edu.co", especialidades: ["Química Orgánica"], materias_asignadas: [{materia_id: matIds[12], periodo: "2025-1", horario: "Vie 4pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF014", nombre: "Dr. Andrés Morales", email: "andres.prof@uni.edu.co", especialidades: ["Álgebra Abstracta"], materias_asignadas: [{materia_id: matIds[13], periodo: "2025-1", horario: "Lun 5pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF015", nombre: "Dra. Camila Ortiz", email: "camila.prof@uni.edu.co", especialidades: ["Historia Contemporánea"], materias_asignadas: [{materia_id: matIds[14], periodo: "2025-1", horario: "Mar 6pm"}, {materia_id: matIds[15], periodo: "2025-2", horario: "Mie 7pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF016", nombre: "Enf. Sebastián Castro", email: "sebastian.prof@uni.edu.co", especialidades: ["Cuidados Intensivos"], materias_asignadas: [{materia_id: matIds[15], periodo: "2025-1", horario: "Jue 8pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF017", nombre: "Dra. Natalia Ríos", email: "natalia.prof@uni.edu.co", especialidades: ["Física Cuántica"], materias_asignadas: [{materia_id: matIds[16], periodo: "2025-1", horario: "Vie 9am"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF018", nombre: "Dr. Gabriel Mendoza", email: "gabriel.prof@uni.edu.co", especialidades: ["Literatura Latina"], materias_asignadas: [{materia_id: matIds[17], periodo: "2025-1", horario: "Lun 10am"}, {materia_id: matIds[18], periodo: "2025-2", horario: "Mar 11am"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF019", nombre: "Maestra Valentina Jiménez", email: "valentina.prof@uni.edu.co", especialidades: ["Composición Musical"], materias_asignadas: [{materia_id: matIds[18], periodo: "2025-1", horario: "Mie 12pm"}] }).insertedId);
profIds.push(db.profesores.insertOne({ codigo: "PROF020", nombre: "Art. Mateo Navarro", email: "mateo.prof@uni.edu.co", especialidades: ["Pintura Contemporánea"], materias_asignadas: [{materia_id: matIds[19], periodo: "2025-1", horario: "Jue 1pm"}, {materia_id: matIds[0], periodo: "2025-2", horario: "Vie 2pm"}] }).insertedId);
print("Profesores insertados. IDs: " + profIds);

db.inscripciones.insertMany([
  { estudiante_id: estIds[0], materia_id: matIds[0], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Inscrito", calificacion: null },
  { estudiante_id: estIds[1], materia_id: matIds[1], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Cursando", calificacion: 2.5 },
  { estudiante_id: estIds[2], materia_id: matIds[2], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Aprobado", calificacion: 4.9 },
  { estudiante_id: estIds[3], materia_id: matIds[3], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Reprobado", calificacion: 2.0 },
  { estudiante_id: estIds[4], materia_id: matIds[4], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Retirado", calificacion: null },
  { estudiante_id: estIds[5], materia_id: matIds[5], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Inscrito", calificacion: null },
  { estudiante_id: estIds[6], materia_id: matIds[6], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Cursando", calificacion: 3.5 },
  { estudiante_id: estIds[7], materia_id: matIds[7], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Aprobado", calificacion: 4.2 },
  { estudiante_id: estIds[8], materia_id: matIds[8], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Reprobado", calificacion: 1.8 },
  { estudiante_id: estIds[9], materia_id: matIds[9], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Retirado", calificacion: null },
  { estudiante_id: estIds[10], materia_id: matIds[10], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Inscrito", calificacion: null },
  { estudiante_id: estIds[11], materia_id: matIds[11], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Cursando", calificacion: 3.0 },
  { estudiante_id: estIds[12], materia_id: matIds[12], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Aprobado", calificacion: 4.6 },
  { estudiante_id: estIds[13], materia_id: matIds[13], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Reprobado", calificacion: 2.4 },
  { estudiante_id: estIds[14], materia_id: matIds[14], periodo: "2025-1", fecha_inscripcion: new Date(), estado: "Retirado", calificacion: null },
  { estudiante_id: estIds[15], materia_id: matIds[15], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Inscrito", calificacion: null },
  { estudiante_id: estIds[16], materia_id: matIds[16], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Cursando", calificacion: 4.0 },
  { estudiante_id: estIds[17], materia_id: matIds[17], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Aprobado", calificacion: 3.9 },
  { estudiante_id: estIds[18], materia_id: matIds[18], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Reprobado", calificacion: 2.1 },
  { estudiante_id: estIds[19], materia_id: matIds[19], periodo: "2025-2", fecha_inscripcion: new Date(), estado: "Retirado", calificacion: null }
]);
print("Inscripciones insertadas.");
